# Generated by Django 3.1.2 on 2020-10-20 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('user_age', models.PositiveIntegerField(default=1, verbose_name='年龄')),
                ('user_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
            ],
        ),
    ]
